# Database file generated by ChanLink
# edit only if you know what you are doing!



# contains privledge level of users

user_re_database={

# Syntax:
#   'NICK!USER@HOST' : 10 ,
# where NICK is the _IRC_lower_case_ equivalent of the
# user's nickname (*NOT necessarily just all lowercase
# letters!*), USER the user's username, HOST the user's
# hostname, and 10 is the user's privledge level.  NICK,
# USER, and HOST may contain Python compatible regular
# expressions.
# See readme.txt for privledge level information

    'asdf!.+@.+':0,
    'dustin!.dustin@.+':99,
    'x!.+@.+':20,
    'y!.+@.+':10,

    #'.+!.+@.+':10,
    '.*ban.*!.+@.+':0,
}
